### ISSUE TITLE
Add key ID to emit type.

### ISSUE THREAD

**Issue by miscco** [blockchaindev/aho_corasick#5]
Hi,

currently if one parses the text, one get a vector containing the keyword itself (Plus start and end of it). In many cases however, the convenient output would be the ID of the keyword in the provided keyword list, e.g in the provided example

``` c++
aho_corasick::trie trie;
trie.insert("hers");
trie.insert("his");
trie.insert("she");
trie.insert("he");
auto result = trie.parse_text("ushers");
```

One should be able to do

``` c++
std::cout << result.at(0).get_keyword() <<"\n"
          << result.at(0).get_index() << "\n";
```

And get the output

```
she
2
```

As far as i understand the algorithm the trie nodes should be indexed themselves so this should be quite straightforward. Thoughts?

**Comment by cjgdev** [comment]
You're quite right, I made similar changes for another project using the library and the work was straight forward. I would be willing to accept a pull request if you are offering to contribute it?

**Comment by miscco** [comment]
@blockchaindev I tried for some hours, but i got some strange compiler warnings. I will have a look if i can find some spare time this WE.

**Comment by cjgdev** [comment]
Ok I've dug out some of the steps I took to make the changes, this should get you 90% of the way there. The basics are:
1. Add a member to the emit class to store the index.
2. Update the emit constructor to take the index as a second parameter.
3. Update the emit copy constructor to store the index when the object is copied by API users.
4. Modify the state class and change the type of the emit_collection to a set<tuple<string_type, size_t>> (now store unique pairs of pattern/index tuples).
5. Update the state::add_emit functions to store the type (ie. d_emits.insert(make_tuple(keyword, index)).
6. Add a member to basic_trie to store the auto-incrementing index counter.
7. Update the basic_trie constructor to initialize the index counter to 0.
8. Modify the basic_trie::insert function to pass the index to the state::add_emit function.
9. Modify the basic_trie::store_emits function to use std::get<0> and std::get<1> to access the tuple members and return them in collected_emits.

**Comment by miscco** [comment]
@blockchaindev That is nearly what i did. I guess i overdid it trying to use a std::pair that made things more complicate than necessary

**Comment by miscco** [comment]
So this seems to work #6 . I went for std::pair rather than tuple but i think this is cleaner.

**Comment by cjgdev** [comment]
Thanks for the pull request, this has now been merged
